env:
  browser: true
  node: true
  jasmine: true
extends:
  - airbnb
  - eslint-config-prettier
plugins:
  - prettier
rules:
  prettier/prettier: error
  react/prefer-stateless-function: 0
  react/jsx-filename-extension: 0
  react/require-default-props: 0
  react/forbid-prop-types: 0
  jsx-a11y/no-static-element-interactions: 0
